### ISSUE TITLE
window.xnft is undefined after hot reload

### ISSUE THREAD

**Issue by metamania01** [coral-xyz/xnft-quickstart#11]
If you add some code, in the dev hot reload mode, the window.xnft is undefined and forces you to exit simulator and enter again to emit the connect event. 

It's annoying dev experience!

**Comment by wentokay** [comment]
thanks for raising the issue @metamania01 this should now be fixed with https://github.com/coral-xyz/xnft-quickstart/pull/17 let us know if you run into problems with it
