### ISSUE TITLE
yarn bundle error

### ISSUE THREAD

**Issue by iqbalutomo** [coral-xyz/xnft-quickstart#44]
Hello I just tried to create a project in backpack using `xnft-quickstart`, but when I try `yarn build` an error like this appears:

<img width="642" alt="Screen Shot 2023-07-20 at 17 24 11" src="https://github.com/coral-xyz/xnft-quickstart/assets/73095492/53ccb1d7-9f8d-4c13-a421-ac73141c9564">

is this an issue from the `xnft-quickstart` repo? please help sir🙏

**Comment by iqbalutomo** [comment]
The problem has been resolved, there are 2 errors that appear:
<img width="424" alt="image" src="https://github.com/coral-xyz/xnft-quickstart/assets/73095492/cedfd695-f18c-4351-8682-ef249471dbb2">

the error lies in value, which is expecting an `object` but receiving a `string` and `storage` key unrecognized.

but in the written documentation the contact key is filled with a string type:
<img width="588" alt="image" src="https://github.com/coral-xyz/xnft-quickstart/assets/73095492/4279086f-3d70-4289-b5a3-2dee37815f3a">

looks like the documentation in the manifest section needs to be updated, thanks✨

**Comment by iqbalutomo** [comment]
Sorry in advance, my `xnft` version needs to be updated and it has been solved🚀, apologies in advance. thank you🙏

**Comment by metaproph3t** [comment]
how did you resolve this issue?

I'm running into the same problem
